//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molar_mass_calculator {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Elements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Elements() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Molar_mass_calculator.Elements", typeof(Elements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 227.00.
        /// </summary>
        internal static string Ac {
            get {
                return ResourceManager.GetString("Ac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 107.87.
        /// </summary>
        internal static string Ag {
            get {
                return ResourceManager.GetString("Ag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 26.98.
        /// </summary>
        internal static string Al {
            get {
                return ResourceManager.GetString("Al", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 243.00.
        /// </summary>
        internal static string Am {
            get {
                return ResourceManager.GetString("Am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 39.95.
        /// </summary>
        internal static string Ar {
            get {
                return ResourceManager.GetString("Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 74.92.
        /// </summary>
        internal static string As {
            get {
                return ResourceManager.GetString("As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 210.00.
        /// </summary>
        internal static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 196.97.
        /// </summary>
        internal static string Au {
            get {
                return ResourceManager.GetString("Au", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 10.81.
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 137.33.
        /// </summary>
        internal static string Ba {
            get {
                return ResourceManager.GetString("Ba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 9.01.
        /// </summary>
        internal static string Be {
            get {
                return ResourceManager.GetString("Be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 270.00.
        /// </summary>
        internal static string Bh {
            get {
                return ResourceManager.GetString("Bh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 208.98.
        /// </summary>
        internal static string Bi {
            get {
                return ResourceManager.GetString("Bi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 247.00.
        /// </summary>
        internal static string Bk {
            get {
                return ResourceManager.GetString("Bk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 79.90.
        /// </summary>
        internal static string Br {
            get {
                return ResourceManager.GetString("Br", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 12.01.
        /// </summary>
        internal static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 40.08.
        /// </summary>
        internal static string Ca {
            get {
                return ResourceManager.GetString("Ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 112.41.
        /// </summary>
        internal static string Cd {
            get {
                return ResourceManager.GetString("Cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 140.12.
        /// </summary>
        internal static string Ce {
            get {
                return ResourceManager.GetString("Ce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 251.00.
        /// </summary>
        internal static string Cf {
            get {
                return ResourceManager.GetString("Cf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 35.45.
        /// </summary>
        internal static string Cl {
            get {
                return ResourceManager.GetString("Cl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 247.00.
        /// </summary>
        internal static string Cm {
            get {
                return ResourceManager.GetString("Cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 285.00.
        /// </summary>
        internal static string Cn {
            get {
                return ResourceManager.GetString("Cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 58.93.
        /// </summary>
        internal static string Co {
            get {
                return ResourceManager.GetString("Co", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 52.00.
        /// </summary>
        internal static string Cr {
            get {
                return ResourceManager.GetString("Cr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 132.91.
        /// </summary>
        internal static string Cs {
            get {
                return ResourceManager.GetString("Cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 63.55.
        /// </summary>
        internal static string Cu {
            get {
                return ResourceManager.GetString("Cu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 268.00.
        /// </summary>
        internal static string Db {
            get {
                return ResourceManager.GetString("Db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 281.00.
        /// </summary>
        internal static string Ds {
            get {
                return ResourceManager.GetString("Ds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 162.50.
        /// </summary>
        internal static string Dy {
            get {
                return ResourceManager.GetString("Dy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 167.26.
        /// </summary>
        internal static string Er {
            get {
                return ResourceManager.GetString("Er", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 252.00.
        /// </summary>
        internal static string Es {
            get {
                return ResourceManager.GetString("Es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 151.96.
        /// </summary>
        internal static string Eu {
            get {
                return ResourceManager.GetString("Eu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 19.00.
        /// </summary>
        internal static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 55.85.
        /// </summary>
        internal static string Fe {
            get {
                return ResourceManager.GetString("Fe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 289.00.
        /// </summary>
        internal static string Fl {
            get {
                return ResourceManager.GetString("Fl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 257.00.
        /// </summary>
        internal static string Fm {
            get {
                return ResourceManager.GetString("Fm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 223.00.
        /// </summary>
        internal static string Fr {
            get {
                return ResourceManager.GetString("Fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 69.72.
        /// </summary>
        internal static string Ga {
            get {
                return ResourceManager.GetString("Ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 157.25.
        /// </summary>
        internal static string Gd {
            get {
                return ResourceManager.GetString("Gd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 72.63.
        /// </summary>
        internal static string Ge {
            get {
                return ResourceManager.GetString("Ge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 1.01.
        /// </summary>
        internal static string H {
            get {
                return ResourceManager.GetString("H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 4.00.
        /// </summary>
        internal static string He {
            get {
                return ResourceManager.GetString("He", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 178.49.
        /// </summary>
        internal static string Hf {
            get {
                return ResourceManager.GetString("Hf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 200.59.
        /// </summary>
        internal static string Hg {
            get {
                return ResourceManager.GetString("Hg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 164.93.
        /// </summary>
        internal static string Ho {
            get {
                return ResourceManager.GetString("Ho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 270.00.
        /// </summary>
        internal static string Hs {
            get {
                return ResourceManager.GetString("Hs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 126.90.
        /// </summary>
        internal static string I {
            get {
                return ResourceManager.GetString("I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 114.82.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 192.22.
        /// </summary>
        internal static string Ir {
            get {
                return ResourceManager.GetString("Ir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 39.10.
        /// </summary>
        internal static string K {
            get {
                return ResourceManager.GetString("K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 83.80.
        /// </summary>
        internal static string Kr {
            get {
                return ResourceManager.GetString("Kr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 138.91.
        /// </summary>
        internal static string La {
            get {
                return ResourceManager.GetString("La", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 6.94.
        /// </summary>
        internal static string Li {
            get {
                return ResourceManager.GetString("Li", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 266.00.
        /// </summary>
        internal static string Lr {
            get {
                return ResourceManager.GetString("Lr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 174.97.
        /// </summary>
        internal static string Lu {
            get {
                return ResourceManager.GetString("Lu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 293.00.
        /// </summary>
        internal static string Lv {
            get {
                return ResourceManager.GetString("Lv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 290.00.
        /// </summary>
        internal static string Mc {
            get {
                return ResourceManager.GetString("Mc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 258.00.
        /// </summary>
        internal static string Md {
            get {
                return ResourceManager.GetString("Md", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 24.31.
        /// </summary>
        internal static string Mg {
            get {
                return ResourceManager.GetString("Mg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 54.94.
        /// </summary>
        internal static string Mn {
            get {
                return ResourceManager.GetString("Mn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 95.95.
        /// </summary>
        internal static string Mo {
            get {
                return ResourceManager.GetString("Mo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 278.00.
        /// </summary>
        internal static string Mt {
            get {
                return ResourceManager.GetString("Mt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 14.01.
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 22.99.
        /// </summary>
        internal static string Na {
            get {
                return ResourceManager.GetString("Na", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 92.91.
        /// </summary>
        internal static string Nb {
            get {
                return ResourceManager.GetString("Nb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 144.24.
        /// </summary>
        internal static string Nd {
            get {
                return ResourceManager.GetString("Nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 20.18.
        /// </summary>
        internal static string Ne {
            get {
                return ResourceManager.GetString("Ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 286.00.
        /// </summary>
        internal static string Nh {
            get {
                return ResourceManager.GetString("Nh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 58.69.
        /// </summary>
        internal static string Ni {
            get {
                return ResourceManager.GetString("Ni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 259.00.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 237.00.
        /// </summary>
        internal static string Np {
            get {
                return ResourceManager.GetString("Np", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 16.00.
        /// </summary>
        internal static string O {
            get {
                return ResourceManager.GetString("O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 294.00.
        /// </summary>
        internal static string Og {
            get {
                return ResourceManager.GetString("Og", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 190.23.
        /// </summary>
        internal static string Os {
            get {
                return ResourceManager.GetString("Os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 30.97.
        /// </summary>
        internal static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 231.04.
        /// </summary>
        internal static string Pa {
            get {
                return ResourceManager.GetString("Pa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 207.20.
        /// </summary>
        internal static string Pb {
            get {
                return ResourceManager.GetString("Pb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 106.42.
        /// </summary>
        internal static string Pd {
            get {
                return ResourceManager.GetString("Pd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 145.00.
        /// </summary>
        internal static string Pm {
            get {
                return ResourceManager.GetString("Pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 209.00.
        /// </summary>
        internal static string Po {
            get {
                return ResourceManager.GetString("Po", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 140.91.
        /// </summary>
        internal static string Pr {
            get {
                return ResourceManager.GetString("Pr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 195.08.
        /// </summary>
        internal static string Pt {
            get {
                return ResourceManager.GetString("Pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 244.00.
        /// </summary>
        internal static string Pu {
            get {
                return ResourceManager.GetString("Pu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 226.00.
        /// </summary>
        internal static string Ra {
            get {
                return ResourceManager.GetString("Ra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 85.47.
        /// </summary>
        internal static string Rb {
            get {
                return ResourceManager.GetString("Rb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 186.21.
        /// </summary>
        internal static string Re {
            get {
                return ResourceManager.GetString("Re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 267.00.
        /// </summary>
        internal static string Rf {
            get {
                return ResourceManager.GetString("Rf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 282.00.
        /// </summary>
        internal static string Rg {
            get {
                return ResourceManager.GetString("Rg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 102.91.
        /// </summary>
        internal static string Rh {
            get {
                return ResourceManager.GetString("Rh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 222.00.
        /// </summary>
        internal static string Rn {
            get {
                return ResourceManager.GetString("Rn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 101.07.
        /// </summary>
        internal static string Ru {
            get {
                return ResourceManager.GetString("Ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 32.06.
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 121.76.
        /// </summary>
        internal static string Sb {
            get {
                return ResourceManager.GetString("Sb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 44.96.
        /// </summary>
        internal static string Sc {
            get {
                return ResourceManager.GetString("Sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 78.97.
        /// </summary>
        internal static string Se {
            get {
                return ResourceManager.GetString("Se", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 269.00.
        /// </summary>
        internal static string Sg {
            get {
                return ResourceManager.GetString("Sg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 28.09.
        /// </summary>
        internal static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 150.36.
        /// </summary>
        internal static string Sm {
            get {
                return ResourceManager.GetString("Sm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 118.71.
        /// </summary>
        internal static string Sn {
            get {
                return ResourceManager.GetString("Sn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 87.62.
        /// </summary>
        internal static string Sr {
            get {
                return ResourceManager.GetString("Sr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 180.95.
        /// </summary>
        internal static string Ta {
            get {
                return ResourceManager.GetString("Ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 158.93.
        /// </summary>
        internal static string Tb {
            get {
                return ResourceManager.GetString("Tb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 98.00.
        /// </summary>
        internal static string Tc {
            get {
                return ResourceManager.GetString("Tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 127.60.
        /// </summary>
        internal static string Te {
            get {
                return ResourceManager.GetString("Te", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 232.04.
        /// </summary>
        internal static string Th {
            get {
                return ResourceManager.GetString("Th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 47.87.
        /// </summary>
        internal static string Ti {
            get {
                return ResourceManager.GetString("Ti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 204.38.
        /// </summary>
        internal static string Tl {
            get {
                return ResourceManager.GetString("Tl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 168.93.
        /// </summary>
        internal static string Tm {
            get {
                return ResourceManager.GetString("Tm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 294.00.
        /// </summary>
        internal static string Ts {
            get {
                return ResourceManager.GetString("Ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 238.03.
        /// </summary>
        internal static string U {
            get {
                return ResourceManager.GetString("U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 50.94.
        /// </summary>
        internal static string V {
            get {
                return ResourceManager.GetString("V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 183.84.
        /// </summary>
        internal static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 131.29.
        /// </summary>
        internal static string Xe {
            get {
                return ResourceManager.GetString("Xe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 88.91.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 173.05.
        /// </summary>
        internal static string Yb {
            get {
                return ResourceManager.GetString("Yb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 65.38.
        /// </summary>
        internal static string Zn {
            get {
                return ResourceManager.GetString("Zn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 91.22.
        /// </summary>
        internal static string Zr {
            get {
                return ResourceManager.GetString("Zr", resourceCulture);
            }
        }
    }
}
